### PR TITLE
Add Wind Heading and Wave Height and Period

### PR DESCRIPTION
**Pull request by moorgrove**

### CODE REVIEW

**Comment by astrandb** [comment]
Thank you for the contribution. 
Can you please tell me on what station(s) these parameters are reported.

I have a few minor comments on the code that I will return tomorrow or the day after.

**Comment by moorgrove** [comment]
Hi,

The wave height and period is reported at Brofjorden Angöring as I know but it could be in more locations that I'm not aware of. The wind heading is reported in many places but Tån and Stretudden is two of them. 

Kind regards

**Comment by astrandb** [comment]
I have tried to adhere to Home Assistant developer guidelines for the presentation of sensor data. In the official weather entity the wind direction is called "wind_bearing" internally (I missed that - noone is perfect). I beleive "Vindriktning" is the normal term in swedish though. The value is either a float or 1-3 letter cardinal direction. Not both. I chose the cardinal direction, same as most other weather providers. So my suggestion is that we stick to cardinal letters to reduce clutter. Same should apply to wave direction (or bearing).
In an ideal world there should only be one source for these bearing values. It should be up to the user to select in the UI if the direction should be presented as "W" or 270. But that is a topic for architectural discussion in HA.

**Comment by moorgrove** [comment]
I totally get the one value for each entity and that cardinal is much easier to read if you don't want to do anything more than presenting the value. My intention with a float value is to make more with the direction than just present it as it is. A float value can be used to present a history graph to see if the wind has changed direction or used with custom compass card.

Skärmavbild 2023-11-22 kl  11 58 45

I will move "Wave Height and Period" to a separate branch so it can be merged and this pull request to be closed.

**Comment by astrandb** [comment]
OK, you have convinced me that numeric sensor for direction can be useful. I suggest that
```python
entity_registry_enabled_default=False,
```
is added to the sensor description. The user can then activate the sensor if needed.

PS I liked the compass card. I will use it myself.

**Comment by moorgrove** [comment]
Sounds perfect. Do you want me to create a new branch for the numeric sensor and close this pull request now that we have a separate pull request for the wave height and period? And do you have any suggestion for the naming of the entity instead of heading?

**Comment by astrandb** [comment]
Yes, I think it will be cleaner to close this PR and start a new one. I suggest that we use the term 'wind bearing' as this is used in the internal weather entity. However, the official integration for Netatmo uses 'Direction' so it is not consequent whatever we term choose.
I still think 'vindriktning' sounds better in Swedish.
The name change will be a breaking change but there are not that many users affected so I hope we will survive the storm...

**Comment by astrandb** [comment]
Taken care of in other PRs

**Pull request closed without merging**
